[repository]
name = "hyprkool"
authors = ["thrombe"]
# the first hash is the Hyprland commit hash, and the second is your pluginâ€™s corresponding commit hash.
commit_pins = [
    ["e93fbd7c4f991cb8ef03e433ccc4d43587923e15", "cba2fbccaed94aa935a72c77d859c0218002a6ed"], # v0.39.0 0.5.3
    ["fe7b748eb668136dd0558b7c8279bfcd7ab4d759", "cba2fbccaed94aa935a72c77d859c0218002a6ed"], # v0.39.1 0.5.3
    ["cba1ade848feac44b2eda677503900639581c3f4", "ca8e5b9c9c58d2c579d1383dbdf5919ad60c6589"], # v0.40.0 0.6.0
    ["ea2501d4556f84d3de86a4ae2f4b22a474555b9f", "6f6915de9dff1c24a27249c9f5f5f1802be33ebf"], # v0.41.0 0.7.0
    ["9e781040d9067c2711ec2e9f5b47b76ef70762b3", "6f6915de9dff1c24a27249c9f5f5f1802be33ebf"], # v0.41.1 0.7.0
    ["918d8340afd652b011b937d29d5eea0be08467f5", "3f56d829b44218d70867886b91d9f697d8ad9f68"], # v0.41.2 0.7.1
]

[hyprkool]
# description = ""
authors = ["thrombe"]
output = "plugin/build/libhyprkool.so"
build = [
    "make plugin"
]
